# CUSTOMER SATISFACTION IN AN AIRLINE

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('Invistico_Airline.csv')
df.head(5)

,satisfaction,Gender,Age,Type of Travel,Class,Flight Distance,Departure/Arrival time convenient,Food and drink,Inflight wifi service,Online support,Ease of Online booking,On-board service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Female,65,Personal Travel,Eco,265,0,0,2,2,3,3,3,5,3,2,0,0.0
1,satisfied,Male,47,Personal Travel,Business,2464,0,0,0,2,3,4,4,2,3,2,310,305.0
2,satisfied,Female,15,Personal Travel,Eco,2138,0,0,2,2,2,3,4,4,4,2,0,0.0
3,satisfied,Female,60,Personal Travel,Eco,623,0,0,3,3,1,1,1,4,1,3,0,0.0
4,satisfied,Female,70,Personal Travel,Eco,354,0,0,4,4,2,2,2,4,2,5,0,0.0

In [3]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
df['satisfaction']=l.fit_transform(df['satisfaction'])
df.head(5)

,satisfaction,Gender,Age,Type of Travel,Class,Flight Distance,Departure/Arrival time convenient,Food and drink,Inflight wifi service,Online support,Ease of Online booking,On-board service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,1,Female,65,Personal Travel,Eco,265,0,0,2,2,3,3,3,5,3,2,0,0.0
1,1,Male,47,Personal Travel,Business,2464,0,0,0,2,3,4,4,2,3,2,310,305.0
2,1,Female,15,Personal Travel,Eco,2138,0,0,2,2,2,3,4,4,4,2,0,0.0
3,1,Female,60,Personal Travel,Eco,623,0,0,3,3,1,1,1,4,1,3,0,0.0
4,1,Female,70,Personal Travel,Eco,354,0,0,4,4,2,2,2,4,2,5,0,0.0

In [4]:
df.isnull().any()

satisfaction                         False
Gender                               False
Age                                  False
Type of Travel                       False
Class                                False
Flight Distance                      False
Departure/Arrival time convenient    False
Food and drink                       False
Inflight wifi service                False
Online support                       False
Ease of Online booking               False
On-board service                     False
Baggage handling                     False
Checkin service                      False
Cleanliness                          False
Online boarding                      False
Departure Delay in Minutes           False
Arrival Delay in Minutes              True
dtype: bool

In [5]:
x=df[['Departure/Arrival time convenient','Food and drink','Inflight wifi service','Online support','Ease of Online booking','On-board service','Baggage handling','Checkin service','Cleanliness','Online boarding','Departure Delay in Minutes']]
x.head(5)

,Departure/Arrival time convenient,Food and drink,Inflight wifi service,Online support,Ease of Online booking,On-board service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes
0,0,0,2,2,3,3,3,5,3,2,0
1,0,0,0,2,3,4,4,2,3,2,310
2,0,0,2,2,2,3,4,4,4,2,0
3,0,0,3,3,1,1,1,4,1,3,0
4,0,0,4,4,2,2,2,4,2,5,0

In [6]:
from sklearn.model_selection import train_test_split
x1,x2,y1,y2=train_test_split(x,df['satisfaction'],test_size=0.2)

In [7]:
from sklearn import tree
reg=tree.DecisionTreeClassifier()
reg.fit(x1,y1)

DecisionTreeClassifier()

In [8]:
reg.predict(x2)

array([1, 1, 0, ..., 1, 1, 1])

In [9]:
reg.score(x2,y2)

0.8339236218047429